# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Dev Workflow

on:
  push:
    branches:
      - main
    paths:
      - "Definitions/**"
      - ".github/**"
  workflow_dispatch:

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-dev
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-dev Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying EPAC-DEV Policy Changes"
          issue-body: "Please review and approve the changes to be deployed to EPAC-DEV"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Deploy Policy Changes
        uses: ./.github/workflows/deploy-policy.yml
        with:
          pacEnvironmentSelector: epac-dev
          planGitHubEnvironment: EPAC-DEV
          PAC_INPUT_FOLDER: ./Output
          PAC_DEFINITIONS_FOLDER: ./Definitions
          secrets: inherit

  deployRoles:
    name: Deploy epac-dev Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-dev
      planGitHubEnvironment: EPAC-DEV
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  # tenantPlan:
  #   name: Plan tenant
  #   needs: [deployPolicy, deployRoles]
  #   if: |
  #     always()
  #     && !contains(needs.*.result,'failure')
  #   uses: ./.github/workflows/plan.yml
  #   with:
  #     pacEnvironmentSelector: epac-dev
  #     planGitHubEnvironment: EPAC-DEV
  #     PAC_OUTPUT_FOLDER: ./Output
  #     PAC_DEFINITIONS_FOLDER: ./Definitions
  #   secrets: inherit
