# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC PROD Workflow

on:
  push:
    branches:
      - main

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan prod
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-prd
      planGitHubEnvironment: TENANT-PLAN
      PAC_OUTPUT_FOLDER: ./Output/prd
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-dev Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        uses: actions/github-script@v4
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const { data: runs } = await octokit.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'manual-approval.yml',
              status: 'completed',
              conclusion: 'success',
              per_page: 1,
            });
            if (runs.length === 0) {
              throw new Error('No successful manual approval found');
            }
      - name: Deploy Policy Changes
        uses: ./.github/workflows/deploy-policy.yml
        with:
          pacEnvironmentSelector: epac-prd
          planGitHubEnvironment: TENANT-DEPLOY-POLICY
          PAC_INPUT_FOLDER: ./Output
          PAC_DEFINITIONS_FOLDER: ./Definitions
          secrets: inherit

  deployRoles:
    name: Deploy prod Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-prd
      planGitHubEnvironment: TENANT-DEPLOY-ROLES
      PAC_INPUT_FOLDER: ./Output/prd
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit